'use client';

import { Award, Building2, Crown, Medal, Trophy } from 'lucide-react';
import { Card, SectionTitle, Shell } from '@/components/shell';
import { organizations } from '@/lib/data';

export default function Leaderboard() {
  const ranked = [...organizations].sort((a, b) => b.contribution - a.contribution).slice(0, 12);
  return <Shell eyebrow="Commercial leaderboard" title="Recognize the leaders." subtitle="A transparent, simulated view of how local organizations could be celebrated for climate action."><div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><Card><SectionTitle title="Top commercial contributors" detail="Simulated voluntary REP contributions · demonstration only" /><div className="space-y-2">{ranked.map((org, index) => <div key={org.name} className={`flex items-center gap-4 rounded-2xl border p-4 ${index === 0 ? 'border-[#e7c871] bg-[#fffaf0]' : 'border-[var(--border)] bg-[var(--background)]'}`}><div className="flex size-9 shrink-0 items-center justify-center rounded-full font-display text-sm font-semibold" style={{ background: index < 3 ? ['#f8df93', '#dde4ea', '#ebc49f'][index] : '#e8f0e8', color: '#315c4d' }}>{index + 1}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-sm font-semibold">{org.name}</p>{index === 0 && <Crown size={14} className="text-[#be8a25]" />}</div><p className="text-[11px] text-[var(--muted)]">{org.industry} · {org.certification} level</p></div><div className="text-right"><p className="font-display text-base font-semibold">${org.contribution.toLocaleString()}</p><p className="text-[10px] font-bold text-moss">{org.impact} tCO₂e modeled</p></div></div>)}</div></Card><div className="space-y-4"><Card><SectionTitle title="Industry momentum" detail="Participation by sector" /><div className="space-y-4">{['Healthcare', 'Food & beverage', 'Education', 'Professional services', 'Nonprofit & faith'].map((sector, index) => <div key={sector}><div className="mb-1 flex justify-between text-xs"><span>{sector}</span><span className="font-bold">{[88, 76, 69, 57, 43][index]}%</span></div><div className="h-2 overflow-hidden rounded-full bg-[#e8eee9]"><div className="h-full rounded-full bg-moss" style={{ width: `${[88, 76, 69, 57, 43][index]}%` }} /></div></div>)}</div></Card><Card className="bg-moss text-white"><Award size={23} className="text-lime" /><h3 className="mt-5 font-display text-xl font-semibold">Climate leadership awards</h3><p className="mt-2 text-sm leading-6 text-white/70">A recognition layer turns voluntary action into a visible local norm — and gives every business a reason to keep climbing.</p><div className="mt-6 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-white/10 p-3"><Trophy size={16} className="mx-auto text-lime" /><p className="mt-2 text-[10px] text-white/70">Pioneer</p></div><div className="rounded-xl bg-white/10 p-3"><Medal size={16} className="mx-auto text-lime" /><p className="mt-2 text-[10px] text-white/70">Builder</p></div><div className="rounded-xl bg-white/10 p-3"><Building2 size={16} className="mx-auto text-lime" /><p className="mt-2 text-[10px] text-white/70">Neighbor</p></div></div></Card></div></div></Shell>;
}
