'use client';

import dynamic from 'next/dynamic';
import { Activity, ArrowDownRight, ArrowUpRight, Building2, CircleDollarSign, Factory, Leaf, Target, Users } from 'lucide-react';
import { motion } from 'framer-motion';
import { activity, contributionTrend, organizations, participatingOrganizations, sourceNotes, totalContributions } from '@/lib/data';
import { Card, SectionTitle, Shell } from '@/components/shell';
import { ContributionChart, ImpactChart } from '@/components/charts';

const OrganizationMap = dynamic(() => import('@/components/map'), { ssr: false, loading: () => <div className="flex h-full min-h-[360px] items-center justify-center rounded-2xl bg-mint text-sm text-moss">Loading live map…</div> });
const currency = (n: number) => `$${(n / 1000).toFixed(n >= 100000 ? 0 : 1)}k`;

function Kpi({ label, value, change, icon: Icon, tone = 'green' }: { label: string; value: string; change: string; icon: React.ElementType; tone?: 'green' | 'coral' | 'blue' | 'gold' }) { const tones = { green: 'bg-mint text-moss dark:bg-[#1d3a2e] dark:text-lime', coral: 'bg-[#fff0eb] text-coral dark:bg-[#3b2824]', blue: 'bg-[#edf1ff] text-[#5567a2] dark:bg-[#252d49]', gold: 'bg-[#fff7dc] text-[#9e7822] dark:bg-[#3d3420]' }; return <Card className="relative overflow-hidden"><div className={`mb-5 flex size-9 items-center justify-center rounded-xl ${tones[tone]}`}><Icon size={18} /></div><p className="text-[12px] font-medium text-[var(--muted)]">{label}</p><p className="mt-1 font-display text-2xl font-semibold tracking-tight">{value}</p><div className="mt-3 flex items-center gap-1 text-[11px] font-bold text-moss dark:text-lime"><ArrowUpRight size={13} />{change}<span className="font-normal text-[var(--muted)]">vs last month</span></div></Card>; }

export default function Dashboard() { return <Shell><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Commercial members" value="64" change="+12.3%" icon={Building2} /><Kpi label="Simulated funding" value={currency(totalContributions)} change="+18.7%" icon={CircleDollarSign} tone="coral" /><Kpi label="Community impact" value="78 t" change="+24.9%" icon={Leaf} tone="gold" /><Kpi label="Annual goal" value="71%" change="On track" icon={Target} tone="blue" /></div>
      <div className="mt-4 grid gap-4 xl:grid-cols-[1.45fr_1fr]"><Card className="min-h-[360px]"><SectionTitle title="Contribution momentum" detail="Simulated voluntary REP funding · 2025 / 26" /><div className="mb-4 flex items-end gap-3"><span className="font-display text-3xl font-semibold tracking-tight">$63.5k</span><span className="rounded-full bg-mint px-2 py-1 text-[10px] font-bold text-moss dark:bg-[#1d3a2e] dark:text-lime">+22.4%</span></div><div className="h-[245px]"><ContributionChart /></div></Card><Card className="min-h-[360px]"><SectionTitle title="Annual goal" detail="$90k simulated community investment target" /><div className="relative mx-auto mt-4 flex size-48 items-center justify-center"><div className="absolute inset-0 rounded-full" style={{ background: 'conic-gradient(#246a57 0deg 256deg, #e6eee8 256deg 360deg)' }} /><div className="absolute inset-[13px] flex flex-col items-center justify-center rounded-full bg-white dark:bg-[#18231f]"><span className="font-display text-4xl font-semibold">71%</span><span className="text-[11px] text-[var(--muted)]">$63.5k of $90k</span></div></div><div className="mt-4 flex justify-center gap-5 text-[11px] text-[var(--muted)]"><span><i className="mr-1 inline-block size-2 rounded-full bg-moss" />Achieved</span><span><i className="mr-1 inline-block size-2 rounded-full bg-[#e6eee8]" />Remaining</span></div></Card></div>
      <div className="mt-4 grid gap-4 xl:grid-cols-[1fr_1.45fr]"><Card><SectionTitle title="Recent activity" detail="Latest movement across the program" href="/directory" /><div className="divide-y divide-[var(--border)]">{activity.map((item, index) => <motion.div initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .08 }} key={item.organization} className="flex items-center gap-3 py-4 first:pt-2"><div className="flex size-9 shrink-0 items-center justify-center rounded-xl text-xs font-bold text-moss" style={{ background: item.color }}>{item.organization.split(' ').map((word) => word[0]).slice(0, 2).join('')}</div><div className="min-w-0 flex-1"><p className="truncate text-[12px] font-semibold">{item.organization}</p><p className="truncate text-[11px] text-[var(--muted)]">{item.action}</p></div><span className="whitespace-nowrap text-[10px] text-[var(--muted)]">{item.time}</span></motion.div>)}</div></Card><Card><SectionTitle title="Impact trajectory" detail="Cumulative modeled outcomes · tCO₂e and MWh" /><div className="mb-3 flex gap-4 text-[11px] text-[var(--muted)]"><span><i className="mr-1 inline-block size-2 rounded-full bg-coral" />CO₂ reduced</span><span><i className="mr-1 inline-block size-2 rounded-full bg-[#7a9f42]" />Energy saved</span></div><div className="h-[220px]"><ImpactChart /></div></Card></div>
      <div id="map" className="mt-4"><Card><SectionTitle title="Participating organizations" detail={`${participatingOrganizations.length} modeled organizations across Naperville · Map points use public locations`} href="/directory" /><div className="h-[390px] overflow-hidden rounded-2xl"><OrganizationMap /></div></Card></div>
      <div id="sources" className="mt-4 rounded-2xl border border-moss/20 bg-mint/60 p-5 dark:bg-[#1a3027]"><div className="flex items-start gap-3"><Activity size={18} className="mt-0.5 shrink-0 text-moss dark:text-lime" /><div><p className="text-xs font-bold text-moss dark:text-lime">Demonstration data notice</p><p className="mt-1 max-w-4xl text-[11px] leading-5 text-[var(--muted)]">Organization names, categories, and locations are drawn from public sources. All contribution amounts, engagement scores, participation status, and impact metrics are simulated demonstration data — no organization is represented as an actual REP participant unless publicly verified.</p><div className="mt-3 flex flex-wrap gap-2">{sourceNotes.map((source) => <span key={source} className="rounded-full border border-moss/15 bg-white/60 px-2.5 py-1 text-[10px] text-moss dark:bg-white/5 dark:text-lime">{source}</span>)}</div></div></div></div>
    </Shell>; }
