'use client';

import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { contributionTrend, impactTrend } from '@/lib/data';

const tooltipStyle = { border: '1px solid #dfe7e1', borderRadius: 12, background: '#fff', fontSize: 11, boxShadow: '0 10px 30px rgba(20,50,40,.1)' };
export function ContributionChart() { return <ResponsiveContainer width="100%" height="100%"><AreaChart data={contributionTrend} margin={{ top: 10, right: 5, left: -20, bottom: 0 }}><defs><linearGradient id="contribution" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#246a57" stopOpacity={0.28} /><stop offset="100%" stopColor="#246a57" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#e8eeea" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#83928a', fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#83928a', fontSize: 10 }} tickFormatter={(value) => `$${value / 1000}k`} /><Tooltip contentStyle={tooltipStyle} formatter={(value: number) => [`$${value.toLocaleString()}`, 'Funding']} /><Area type="monotone" dataKey="contributions" stroke="#246a57" strokeWidth={2.5} fill="url(#contribution)" /></AreaChart></ResponsiveContainer>; }
export function ImpactChart() { return <ResponsiveContainer width="100%" height="100%"><LineChart data={impactTrend} margin={{ top: 10, right: 5, left: -20, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e8eeea" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#83928a', fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#83928a', fontSize: 10 }} /><Tooltip contentStyle={tooltipStyle} /><Line type="monotone" dataKey="co2" name="CO₂ reduced" stroke="#d78a50" strokeWidth={2.5} dot={false} /><Line type="monotone" dataKey="savings" name="Energy saved" stroke="#7a9f42" strokeWidth={2.5} dot={false} /></LineChart></ResponsiveContainer>; }
export function IndustryChart({ data }: { data: Array<{ industry: string; value: number }> }) { return <ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{ top: 0, right: 12, left: 4, bottom: 0 }}><CartesianGrid horizontal={false} stroke="#e8eeea" /><XAxis type="number" hide /><YAxis type="category" dataKey="industry" axisLine={false} tickLine={false} width={110} tick={{ fill: '#83928a', fontSize: 10 }} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="value" fill="#246a57" radius={[0, 5, 5, 0]} barSize={16} /></BarChart></ResponsiveContainer>; }
