'use client';

import { Menu, Bell, Search, ArrowUpRight } from 'lucide-react';
import { useState } from 'react';
import { Sidebar } from './sidebar';

export function Shell({ children, eyebrow = 'Executive dashboard', title = 'Climate leadership, made visible.', subtitle = 'A live demonstration of commercial momentum toward a cleaner Naperville.' }: { children: React.ReactNode; eyebrow?: string; title?: string; subtitle?: string }) {
  const [open, setOpen] = useState(false);
  return <div className="min-h-screen bg-[var(--background)] text-[var(--foreground)]"><div className="mx-auto flex max-w-[1600px]"><Sidebar open={open} onClose={() => setOpen(false)} /><main className="min-w-0 flex-1"><header className="flex h-[76px] items-center justify-between border-b border-[var(--border)] px-5 sm:px-9"><button className="rounded-lg p-2 hover:bg-black/[.04] lg:hidden" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu size={20} /></button><div className="hidden items-center gap-2 text-[12px] font-medium text-[var(--muted)] sm:flex"><span className="size-2 rounded-full bg-lime" />Program year 2025 / 26</div><div className="ml-auto flex items-center gap-2"><button className="hidden items-center gap-2 rounded-lg border border-[var(--border)] px-3 py-2 text-[12px] text-[var(--muted)] sm:flex"><Search size={14} />Search <kbd className="rounded bg-black/[.05] px-1.5 py-0.5 text-[10px] dark:bg-white/10">⌘ K</kbd></button><button className="rounded-lg p-2 text-[var(--muted)] hover:bg-black/[.04]" aria-label="Notifications"><Bell size={17} /></button></div></header><div className="px-5 py-8 sm:px-9 sm:py-11"><div className="mb-9"><p className="mb-3 text-[11px] font-bold uppercase tracking-[.16em] text-moss dark:text-lime">{eyebrow}</p><div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><h1 className="max-w-3xl font-display text-3xl font-semibold leading-[1.08] tracking-[-.04em] sm:text-[44px]">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--muted)] sm:text-[15px]">{subtitle}</p></div><button className="flex w-fit items-center gap-2 rounded-xl bg-moss px-4 py-3 text-xs font-bold text-white shadow-lg shadow-moss/15 transition hover:-translate-y-0.5 hover:bg-[#1f5949]">Share report <ArrowUpRight size={14} /></button></div></div>{children}</div></main></div></div>;
}

export function SectionTitle({ title, detail, href }: { title: string; detail?: string; href?: string }) { return <div className="mb-4 flex items-end justify-between gap-3"><div><h2 className="font-display text-[17px] font-semibold tracking-tight">{title}</h2>{detail && <p className="mt-1 text-xs text-[var(--muted)]">{detail}</p>}</div>{href && <a className="text-xs font-bold text-moss hover:underline dark:text-lime" href={href}>View all <ArrowUpRight size={13} className="inline" /></a>}</div>; }

export function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-2xl border border-[var(--border)] bg-white p-5 shadow-panel dark:bg-[#18231f] dark:shadow-panel-dark sm:p-6 ${className}`}>{children}</section>; }
